### ISSUE TITLE
App crashes and data loss issue when adding 2000 PDFs

### ISSUE THREAD

**Issue by jaxsnjohnson** [DSPaul/COMPASS#19]
**Describe the bug**
The app crashes and loses all data when around 2000 PDFs are added. App will scan PDFs and seemingly add them before stalling out then crashing.  Reopening the app it does not retain any of the data from the imported items, even ones imported before the 2000 were added.

**Expected behavior**
The app should be able to handle and store a vast volume of PDFs or allow for more than one "library" of books to be saved.  It would be nice for each edition of D&D.

**System info (please complete the following information):**
 - OS: Windows 11

**Comment by DSPaul** [comment]
2000 pdf's is quite the stresstest and I will warn you that when you get them all added, the app might be extremely laggy, the most I ever tested is 150 pdf's so this is unexplored territory.

The data loss is expected, the save function is only called after the entire import has completed because that's more efficient but if it crashes halfway through, it's indeed a pain in the ass. 

I'll test the performance impact of saving after every pdf is imported and if it's very small I'll make that the new default, if it isn't, I'll make it an option intended voor large imports only because that takes ages anyway so who cares if it's a little slower. 

As for why it crashes, could you attach the all.log file? It can be found by opening COMPASS and going to preferences>manage data>browse local files and you'll find it in the logs folder. Or go directly to %appdata%\COMPASS\logs.

**Comment by DSPaul** [comment]
Also about the multiple libraries, this is a feature that is already present! It's called collections and you can find them at the top where it currently says "default". You can create, delete and rename collections with the buttons right beside it.

**Comment by DSPaul** [comment]
Without a crash log I can't really do much and the file loss on crash has been addressed so I will close this due to inactivity given that it has been close to 2 months.
