### ISSUE TITLE
Fetch meta data with ISBN number?

### ISSUE THREAD

**Issue by DraftDodger42** [DSPaul/COMPASS#21]
I like how adding an item via ISBN number will fetch data like author, release date, etc. 

I would love to be able to have this fetch happen for PDFs I have locally that also have an ISBN number.

**Comment by DSPaul** [comment]
This seems doable and I agree that it would be a nice feature to have. The main challenge would be to reliable find the ISBN number in the pdf text because there is no real standard way of doing it but its pretty much always in on the first 2-4 pages so it shouldn't be that hard to find. I'll look into it.

**Comment by DSPaul** [comment]
Done, it will be included in the next release.

**Comment by DraftDodger42** [comment]
awesome!
