### ISSUE TITLE
Adding an extra lay-out: Folders

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#25]
Hi!

I wonder if it would be feasible to add another lay-out to the options, namely 'Folders', based on your folder structure. 
It would also be neat if you could then right click a folder (similarly to bulk edits) and give that folder and it's contents (even files a few folders deep) the tags you desire. It would make sorting and giving metadata to an archive much easier. 

At the moment, when I readd my main folder, it scans for additions, but adds them in an unsorted bunch (or well, if I want sorted by date added or something) at the bottom. That's no issue if you only have 1 system with maybe 2-3 extra files since the last scan, but it can become problematic if you add maybe a hundred files of a dozen different systems per scan. 

Thanks for considering!

**Comment by DSPaul** [comment]
That's an interesting request because the reason I created this app was because I find folders to be an awful way to organize files. Folders group your files in a predetermined way where the tagging system allows you to group them in a dynamic way instead. A classic example to show why folders suck is the typical school folder:
- `first grade`
   - `math`
   - `english`
   - `history`
- `second grade`
   - `math`  
   - `english`
   - `history`
- `...`

If at any point you wanted to see all you files related to math regardless of what grade it was in, you can't. With a tagging system however, you can make a tag tree like this:

- `GRADE`
  - `first`
  - `second`
  - `...`
- `COURSES`
  - `math`
  - `english`
  - `history`

You retain the same functionality of folders (so opening the `first grade\math` folder is equivalent to filtering on the `first grade` & `math`  tags) but you also gain new functionality like seeing all you files from second grade or all your files from history regardless of grade. I know all of this is all really obvious but the point that I am trying to make is that a tagging system is a direct replacement for a folder system. Adding a folder layout into COMPASS is essentially reintroducing the folder system and then you have two competing system to perform the same task: grouping files. 

There is also already the collections system to separate files that have nothing to do with each other, perfect for separating different rpg systems for example. Adding a folder layout with support for nested folders is also more or less equivalent to coding an entire file explorer which is far from trivial.

With all of this said I hope you can understand why a folder layout it not something I feel like adding, **however** that doesn't mean your problem isn't valid and shouldn't be solved. As far as I understand, you would like to assign tags to folders and then whenever you import a file from that folder, that file should automatically get the tags that are associated with that folder. So the better solution here in my opinion is not to add a folder layout in COMPASS but to create a system that lets you define a relation between tags in COMPASS and folders in Windows so that during import, it looks at the folder it is in and applies the tags that are associated with that folder, basically converting the folder path to a list of tags. 

I hope that explanation made sense but to come back to the school folder as an example, you could associate the `first grade` folder with the `GRADE`>`first` tag and associate the `math` folder with the `COURSES`>`math` tag so that when you import a file from the `first grade\math` folder, it would automatically get the `math` & `first` tags.

**Comment by Mifgan** [comment]
Yeah, the proposed solution of being able to define relations between the folders and tags would be indeed the goal I was looking for. The need (sometimes) to look and search files sorted in folders can already be easily satisfied by spending way too much time staring at my explorer. Thanks! 

It would adding my few thousands folders of sorted files to COMPASS a lot easier.

**Comment by DSPaul** [comment]
> my few thousands folders

 The TTRPG community never seize to amaze me and I am starting to understand why this app was such a hit because I cannot even begin to imagine how much of a pain it must be to find anything in there.

**Comment by Mifgan** [comment]
Most other apps that allow fuzzy search or metadata tagging / sorting, don't allow custom folder structures. If you've spent years sorting your archive to your own preferences, it's a bit salty that some software (looking at you, Calibre / Readarr) upends your structure. Having a large archive of system agnostic files can be a pain to browse through to find that one resource you remember buying 8 years ago, but you'd really want to read through for your game in 2 days. 
Your app could solve both these issues. :) 

I might even be tempted to make a collection to sort other non-TTRPG pdfs through COMPASS.
