### ISSUE TITLE
Amount of files

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#39]
Hi, 

Could there be somewhere in the main view (maybe in the top bar) an indicator of the amount of files in your current view and maybe also how many are visible with your filters on, ie 15 of 200 (files visible). 

![afbeelding](https://user-images.githubusercontent.com/13572985/223455957-e6bc8afd-4112-4187-bd91-9f30521e64fc.png)

Thanks for considering!

**Comment by DSPaul** [comment]
The idea has also crossed my mind, I mainly just need to decide where I want to put it. I'm thinking of adding a small bar at the bottom where I can display all kinds of situational info in the future, comparable to what VS Code has as shown in this screenshot. The internet indicator for example could also go there so that the top bar is reserved for actions alone.  I have already taken quite a bit of inspiration from vs code's UX as you might be able to tell. 

![afbeelding](https://user-images.githubusercontent.com/35136955/223461490-d5e169d3-6efd-4b38-b779-f25a98e73d24.png)

**Comment by DSPaul** [comment]
Added in 1.3.0
