### ISSUE TITLE
Can't add author without ";"

### ISSUE THREAD

**Issue by DraftDodger42** [DSPaul/COMPASS#46]
**Describe the bug**
When editing the author field, if you don't add a semicolon to the end of the name, the change doesn't stick. You also can't pick an author from the drop down (same issue I think)

 - OS: Win 10
 - Release Version 1.1.3

**Comment by DSPaul** [comment]
These are different issues. 
- The needed ";" is a limitation of the UI element I use. I made an issue for it a few months ago that you can check out here: nilayjoshi89/BlackPearl#24. I might have to ditch it and come up with my own solution though because he didn't show much interest in fixing it. 
- The not being able to pick an author is strange and something I cannot reproduce. You should be able to either click on the names as they appear or if you already started typing you can navigate to them using the up and down arrow keys and press enter to add one. Can you confirm that both of these methods don't work for you?

**Comment by DraftDodger42** [comment]
Sorry I must be losing my mind. Issue two I can't reproduce either. Please ignore that one.
