### ISSUE TITLE
Filename in COMPASS

### ISSUE THREAD

**Issue by Mifgan** [DSPaul/COMPASS#52]
When importing files, COMPASS shows sometimes a different name than the filename itself. This is likely based metadata?
Sadly not all creators set this metadata in something relevant or readable. 

ie the file `HotOE - Handout #02 - Article - The London Times (Jan 15, 1923)` gets named `Microsoft PowerPoint - Presentation1` in COMPASS. That's painful if you did your best to rename the files in your archive. 
![image](https://user-images.githubusercontent.com/13572985/235493108-fc812035-e4b1-46b2-9de5-11b43c314c5b.png)

Suggestion: 
- Either names of files in COMPASS = filename.
- Or a dropdown in the settings with the default names (current situation) and the filenames to choose from. 

I wonder if said setting could be changed it could be done on files already imported, but from monitored folders, or if I should remove all files from COMPASS and reimport them later?

Thanks!

**Comment by DSPaul** [comment]
PDF's have a build in metadata field "Title" which is chosen over the file name if it is set. I have chosen to use the PDF metadata instead of the filename in those cases because the metadata field is empty by default and has to be explicitly set by the creator of the pdf so it is usually better than the file name which is often pretty meaningless. It seems however from your example that powerpoint sets this field while generating a pdf so the assumption that the "Title" metadata is only filled when done so intentionally by the creator is wrong. 

I am working currently working on a new and improved metadata system as I have shown in the discord that has a priority system build in so I will split up the filename and pdf metadata as separate sources so you can order them however you would like. The new system would also allow you to automatically get and overwrite metadata of your choice for files of your choice so you will be able to use that to change the titles of those files back automatically.

**Comment by DSPaul** [comment]
In v1.5.0, you can choose whether the file name or "Title" metadata of a pdf should be preferred, the default order still prefers the metadata of the pdf but you can now change it in the metadata tab of the settings.
