### ISSUE TITLE
Auto scroll when i click on an item

### ISSUE THREAD

**Issue by lucastucious** [DSPaul/COMPASS#61]
**Describe the bug**
When in click on an item, the view is scrolling
**Expected behavior**
no scrolling

**Screenshots/files**

https://github.com/DSPaul/COMPASS/assets/28046122/c3ddc7aa-c44a-4a24-9c80-e60ee153ee33

**System info (please complete the following information):**
 - OS: Windows 10
 - Release Version 1.5.1

**Comment by DSPaul** [comment]
I have never seen that behaviour, very bizar. Does this happen consistently or was it a one-off random thing?

**Comment by lucastucious** [comment]
Since I import all my books it does this.
But not everytime.

I have to check, but I think it begin when I make a multiple selection in
the first place

Le lun. 30 oct. 2023, 23:49, Paul De Smul ***@***.***> a
écrit :

**Comment by DSPaul** [comment]
I'm pretty sure it has to do with windows scaling being buggy as always. Just to confirm, can you go to your windows display settings and set scaling back to 100% (assuming it wasn't already) and see it that fixes it?

**Comment by DSPaul** [comment]
I have just disabled the auto scrolling for now. This behaviour which was supposed to make sure that if you select an item that is partially out of frame, it scrolls a little so that it is completely in view. But given that it is clearly bugged and causes it to scroll completely out of view, it's better not to have it at all.

**Comment by DSPaul** [comment]
I found the root cause and was able to fix it while keeping the scrolling into view functionality from before.
