### ISSUE TITLE
Tags are cropped in Card view

### ISSUE THREAD

**Issue by lucastucious** [DSPaul/COMPASS#62]
![image](https://github.com/DSPaul/COMPASS/assets/28046122/4799c015-ef21-4513-af2c-729b319be9d6)

**System info (please complete the following information):**
 - OS: Windows 10
 - Release Version1.5.1

**Comment by DSPaul** [comment]
This is unfortunately a known issue, it has to do with a library that I use that massively improves render times, but cannot deal with dynamic sizing, this is the related issue from that library: sbaeumlisberger/VirtualizingWrapPanel#22.
The author is working on a v2 of the library which adds support for this and I have already confirmed fixes this problem but it introduces other bugs in its place so it's not ready yet. 

To determine the size of all the cards, the library will look at the size required to render the first one, and makes all the others the same size. And because the first item in your list doesn't have any tags, no space is reserved for them and all of them will have too little space to render them. You will see that giving the first one a tag will fix it ... until you have a book with multiple lines of tags and the problem comes back as you can see here.
![afbeelding](https://github.com/DSPaul/COMPASS/assets/35136955/00d2a13c-e81f-451c-8f6d-a3bd73705aa0)

What I will do is make sure there is always space reserved for at least 1 line of tags as that should cover most use cases, as for multi line, it's waiting on that v2 update.
